language: ruby
rvm:
- 2.2.3
bundler_args: "--without development production"
before_install:
- gem update --system
- gem --version
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
notifications:
  slack:
    secure: VhAKcAu9bIEwVTFvFaMc3dKgzY0IuxvrSalsoj1/efUfoA7uvdzkAwuqQYd+TspJyX+lJYIR/Nc3D5HYTDoXj4SjWWm4fJmeOx7jit64902z52kEqm4QS+1ezGfB8m1viHn7TJQ1KG2PjBlID9l+IjSAinS3Att5fpTODPimFIuWwnk3jziKNnoaWyb9TAKkDJPIXJ2P08CI06fNrKcd7EAMIu9MYC2TSTaHGxoYm8qkORp5hg0bpTAe4HcoCSRYernzx97hyfVWm/epjXWK3eSQQqdP7GdxTPwZO55sTRKK4QP6J/WNlVIVZxmc2WnRwpTlMACtRUXF8J3BLHmoO6/6chbwC35a3QOKOkyrgM3w+ElIDCGhPO7g4ValAsltyB1iJU3iIIE7U94itX7UibGKvQIMcsweX+yMIXwYc9cEVNrq/PfW4oJOBNiPLL+EKsFi9uEiTrgMD52WE93K/QPmZ+tzk80YoG4rCLQbd/xaDwz7BldD1XdvU4w3qtFkCXQx1bGeg+mrNvW7aBEhSDvl9setm9o6KqAFq5HyIcR4s+t62f+KPJckYTSVmQncso/t5bf8JvZ+2rA3Z+XWMQ9G7CHWecPrdi/x5ItRQvyoycaoDxnQ5wAWj9CUE6oaalEUr0QnhE3FOsUJBxIR5YBmLLLcxnd7gGGrANvlBss=
